############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################
# This plugin was created by: 
# Carlgo11 http://www.carlgo11.com/
# Psgs http://www.psgs.tk/
# Cabbex 
# Get in touch with us:
#
# Join our irc: http://bit.ly/cmdbouncerirc
# 
 
############################################################
# +------------------------------------------------------+ #
# |                  General Settings                    | #
# +------------------------------------------------------+ #
############################################################

# Does this plugin not work? Set "debug" to true and pastie your server.log to an developer
# true/false
debug: false

############################################################
# +------------------------------------------------------+ #
# |                       Settings                       | #
# +------------------------------------------------------+ #
############################################################

# Do you want the plugin to update automaticly when a new version is avible?
auto-update: true

# Do you want to disable the incomming message when a command matches a commnad listed below?
# Example: player types /op, cmd is set to disable = the incomming message won't be blocked. 
# If cmd is not listed below it will be set to true by defualt.

cmd1-disable: true

############################################################
# +------------------------------------------------------+ #
# |                   Listen Commands                    | #
# +------------------------------------------------------+ #
############################################################

# Enter the commands you want the plugin to listen on use the same number on the listening command as on the bouncer command!
# EXAMPLE: cmd1: hi


############################################################
# +------------------------------------------------------+ #
# |                   Bounce Commands                    | #
# +------------------------------------------------------+ #
############################################################

# Enter the commands that you want the plugin to execute when a player types the given command

# EXAMPLE: console1: say hi %player&

